// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_FIREBASE_API_KEY'] ?? '',
    appId: '1:1050784867568:android:0971a4f050353606c54e35',
    messagingSenderId: '1050784867568',
    projectId: 'lapangku-4e610',
    storageBucket: 'lapangku-4e610.firebasestorage.app',
  );

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_FIREBASE_API_KEY'] ?? '',
    appId: '1:1050784867568:web:e31663989aa3d7e8c54e35',
    messagingSenderId: '1050784867568',
    projectId: 'lapangku-4e610',
    authDomain: 'lapangku-4e610.firebaseapp.com',
    storageBucket: 'lapangku-4e610.firebasestorage.app',
    measurementId: 'G-XQWG83XC4N',
  );

}
